# Generated by Django 4.2.16 on 2024-11-27 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sponsors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sponsor',
            name='path_to_logo_dark_mode',
            field=models.CharField(blank=True, help_text='This image will be shown when dark mode is enabled. If not specified, then the default logo specified above will be shown.', max_length=300, null=True, verbose_name='Path to logo for dark mode'),
        ),
    ]
