# Generated by Django 4.2.16 on 2024-10-11 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lectures', '0002_relations'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='content',
        ),
        migrations.AddField(
            model_name='schedule',
            name='schedule_data',
            field=models.JSONField(default=dict, verbose_name='Schedule data (JSON)'),
        ),
    ]
