# Generated by Django 4.2.20 on 2025-04-10 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lectures', '0003_remove_schedule_content_schedule_schedule_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='recording_preferences',
            field=models.CharField(choices=[('DoNotRecord', 'Do not allow recording'), ('Record', 'Allow recording'), ('RecordAndPublish', 'Allow recording and publication on YouTube'), ('RecordPublishAndStream', 'Allow recording, publication and live-streaming on YouTube')], default='DoNotRecord', max_length=30, verbose_name='Lecture recording preferences'),
            preserve_default=False,
        ),
    ]
