version: "3"

services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=zosia
      - POSTGRES_USER=zosia
      - POSTGRES_PASSWORD=zosia

  # Container with web application
  web:
    build:
      context: ./app
      dockerfile: Dockerfile
      target: dev
    image: zosia_dev
    # Main process in container
    command: sleep infinity
    # docker volumes - Host:Container
    volumes:
      - ./app/server:/code/server
      - ./app/client:/code/client
      - ./app/js:/code/js
      - ./app/static:/code/static
      # Node modules installed in container need to be visible in host for local development, IDEs etc.
      # Especially the _reactivated module which is generated on `python manage.py runserver` and contains types for Typescript
      - ./app/node_modules:/code/node_modules
    ports:
      - "8000:8000"
    depends_on:
      - db
    links:
      - db
