# Generated by Django 4.2.16 on 2024-11-27 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conferences', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zosia',
            name='banner',
        ),
    ]
