# Generated by Django 4.2.26 on 2025-11-21 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conferences', '0002_remove_zosia_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='zosia',
            name='dates_are_tba',
            field=models.BooleanField(default=False, verbose_name='Dates are To Be Announced'),
        ),
    ]
