# Generated by Django 4.2.26 on 2025-11-21 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conferences', '0003_zosia_dates_are_tba'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zosia',
            name='lecture_registration_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='zosia',
            name='lecture_registration_start',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Registration for lectures starts'),
        ),
        migrations.AlterField(
            model_name='zosia',
            name='rooming_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='zosia',
            name='rooming_start',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Users room picking starts'),
        ),
    ]
