# Generated by Django 4.2.16 on 2024-10-11 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpreferences',
            name='student_number',
            field=models.CharField(blank=True, default='', help_text='Providing false information risks removal of your application with no refund.', max_length=10),
        ),
    ]
